EXECUTOR_NAME=~/nduginec_evn3/bin/python
TEST_SET_SIZE=700

GPU=0 RUN_NAME=RUN_20_CL_0  EXECUTOR_NAME=$EXECUTOR_NAME CLASS_NUMBER=0  TEST_SET_SIZE=$TEST_SIZE ./run_template.sh &
GPU=0 RUN_NAME=RUN_21_CL_1  EXECUTOR_NAME=$EXECUTOR_NAME CLASS_NUMBER=1  TEST_SET_SIZE=$TEST_SIZE ./run_template.sh &
GPU=1 RUN_NAME=RUN_22_CL_2  EXECUTOR_NAME=$EXECUTOR_NAME CLASS_NUMBER=2  TEST_SET_SIZE=$TEST_SIZE ./run_template.sh &
GPU=1 RUN_NAME=RUN_23_CL_3  EXECUTOR_NAME=$EXECUTOR_NAME CLASS_NUMBER=3  TEST_SET_SIZE=$TEST_SIZE ./run_template.sh &
GPU=2 RUN_NAME=RUN_24_CL_4  EXECUTOR_NAME=$EXECUTOR_NAME CLASS_NUMBER=4  TEST_SET_SIZE=$TEST_SIZE ./run_template.sh &
GPU=2 RUN_NAME=RUN_25_CL_-1 EXECUTOR_NAME=$EXECUTOR_NAME CLASS_NUMBER=-1 TEST_SET_SIZE=$TEST_SIZE ./run_template.sh &